# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: nhs.mft.fhir
canonical: https://hl7.mft.nhs.uk
version: 0.0.1
name: MFT_Genomics
title: "North West Genomics HL7 v2 and FHIR Implementation Guide"
description: Implementation Guide for North West Genomics
releaseLabel: ci-build

status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: Manchester University NHS Foundation Trust
  - url: https://mft.nhs.uk/
  - email: pressoffice@mft.nhs.uk
contact:
  - name: Press Office
    telecom:
      - system: email
        value: pressoffice@mft.nhs.uk
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland"
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2024+

dependencies:
  fhir.r4.ukcore.stu2:
    version: 2.1.0
    uri: https://simplifier.net/guide/ukcoreversionhistory
  hl7.fhir.eu.laboratory:
    version: 0.1.0

FSHOnly: false
# see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
parameters:
  path-binary: input/binary
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  excludexml: 'false'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'false'
  generate:
    - xml
    - json
  path-expansion-params: '../resources/Parameters-exp-params.json'


#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
instanceOptions:
  setMetaProfile: never


pages:
  index.md:
    title: Home
    generation: markdown
  LTW.md:
    title: Genomics Test Workflow [LTW]
    generation: markdown
  LAB-1.md:
    title: Placer Order Management [LAB-1]
    generation: markdown
  LAB-3.md:
    title: Order Results Management [LAB-3]
    generation: markdown
  LAB-4.md:
    title: Work Order Management [LAB-4]
    generation: markdown
  vol4-order.md:
    title: Order Entry Model
    generation: markdown
  testing.md:
    title: Testing
    generation: markdown
  support.md:
    title: Support
    generation: markdown

resources:
  Questionnaire/NW-Genomics-Test-Order:
    name: NW Genomics Test Order Form
    description: NW Genomics Test Order Form
    exampleBoolean: false

menu:
  Home: index.html
  Analysis and Design (Vol 1) :
    Genomics Test Workflow [LTW]: LTW.html
  Interfaces (Vol 2):
    Placer Order Management [LAB-1]: LAB-1.html
    Order Results Management [LAB-3]: LAB-3.html
    Work Order Management [LAB-4]: LAB-1.html
  Data Models (Vol 3):
    Order Entry Model: vol4-order.html
  Artefacts: artifacts.html
  Development:
    Testing: testing.html
    Support: support.html


